(() => {
  const root = document.getElementById('weather-root'); if (!root) return;
  const state = { city: 'London', loading: false, error: '', snapshot: null };
  const esc = value => window.EdgeXV2?.escape ? EdgeXV2.escape(value) : String(value ?? '');
  const cityCoords = { London: [51.5072,-0.1276], Manchester: [53.4808,-2.2426], Madrid: [40.4168,-3.7038], Berlin: [52.52,13.405], Paris: [48.8566,2.3522] };
  function render() { const s = state.snapshot; root.innerHTML = `<div class="edgex-v2-page-head"><div><span class="edgex-v2-eyebrow">Sports context</span><h1>Weather Intelligence</h1><p>Weather is shown to support fixture analysis, not as a general weather or trading product.</p></div><button class="edgex-v2-button" id="weather-refresh" type="button">Refresh</button></div><div class="edgex-v2-toolbar"><select id="weather-city" aria-label="Choose weather location">${Object.keys(cityCoords).map(city => `<option value="${city}">${city}</option>`).join('')}</select></div>${state.loading ? '<div class="edgex-v2-skeleton"></div>' : state.error ? `<div class="edgex-v2-state edgex-v2-state-error"><strong>Weather unavailable</strong><span>${esc(state.error)}</span><button class="edgex-v2-button" id="weather-retry">Try again</button></div>` : s ? `<div class="edgex-v2-grid"><section class="edgex-v2-card"><span class="edgex-v2-kicker">Current conditions</span><h3>${esc(state.city)}</h3><div class="edgex-market-stats"><div><small>Temperature</small><strong>${s.temperature == null ? 'Unavailable' : `${s.temperature}°`}</strong></div><div><small>Rain probability</small><strong>${s.rainProbability == null ? 'Unavailable' : `${s.rainProbability}%`}</strong></div><div><small>Wind</small><strong>${s.wind == null ? 'Unavailable' : s.wind}</strong></div><div><small>Humidity</small><strong>${s.humidity == null ? 'Unavailable' : `${s.humidity}%`}</strong></div></div><p>${esc(s.conditions || 'Conditions unavailable')}</p></section><section class="edgex-v2-card"><span class="edgex-v2-kicker">Fixture impact</span><div class="edgex-v2-state"><strong>Impact unavailable without an associated fixture</strong><span>EdgeX only describes passing, crossing, tempo, handling, or fatigue impact when a real fixture, venue, and weather snapshot are all available.</span></div></section></div>` : '<div class="edgex-v2-state"><strong>No weather context loaded</strong><span>Choose a location to request supported provider data.</span></div>'}`; const select = document.getElementById('weather-city'); if (select) select.value = state.city; select?.addEventListener('change', e => { state.city = e.target.value; load(); }); document.getElementById('weather-refresh')?.addEventListener('click', load); document.getElementById('weather-retry')?.addEventListener('click', load); }
  async function load() { state.loading = true; state.error = ''; render(); try { const [lat,lon] = cityCoords[state.city]; const response = await fetch(`/api/edge-weather?lat=${lat}&lon=${lon}`); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Weather provider unavailable'); state.snapshot = body.snapshot; } catch(error) { state.snapshot = null; state.error = error.message || 'Weather provider unavailable'; } finally { state.loading = false; render(); } }
  render(); load();
})();
