(function () {
  'use strict';
  const V2 = window.EdgeXV2;
  const page = document.body.dataset.edgexPage || 'profile';
  const root = document.getElementById('edgex-account-root');
  if (!root || !V2) return;
  const stored = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
  const empty = (title, message) => V2.stateCard('empty', title, message);
  const shell = (eyebrow, title, intro, body) => `<main class="edgex-page"><div class="edgex-v2-toolbar"><div><div class="edgex-v2-eyebrow">${V2.escape(eyebrow)}</div><h1>${V2.escape(title)}</h1><p class="edgex-page-intro">${V2.escape(intro)}</p></div></div>${body}</main>`;

  function profile() {
    const favoriteCount = V2.favorites().length; const savedCount = stored(V2.STORAGE.saved, []).length; const activity = stored(V2.STORAGE.activity, []);
    return shell('Account / Profile', 'Your EdgeX profile', 'A clear home for your preferences, saved research, and the topics you follow.', `<div class="edgex-account-grid"><section class="edgex-v2-card edgex-profile-card"><div class="edgex-profile-avatar">AM</div><div><h2>Alex Morgan</h2><p>EdgeX member</p><span class="edgex-v2-chip positive">AI workspace</span></div><div class="edgex-stat-grid"><div><strong>${savedCount}</strong><small>saved analyses</small></div><div><strong>${favoriteCount}</strong><small>favorites</small></div><div><strong>${activity.length || '—'}</strong><small>analyses viewed</small></div></div></section><section class="edgex-v2-card"><div class="edgex-v2-eyebrow">Quick actions</div><div class="edgex-account-list"><a href="saved-analysis.html">Saved Analysis <span>→</span></a><a href="favorites.html">Favorites <span>→</span></a><a href="notifications.html">Notifications <span>→</span></a><a href="history.html">History <span>→</span></a><a href="settings.html">Settings <span>→</span></a></div></section></div><section class="edgex-v2-card edgex-section-gap"><div class="edgex-v2-eyebrow">Recent activity</div>${activity.length ? activity.slice(0,5).map(item => `<article class="edgex-saved-row"><div><strong>${V2.escape(item.subject || item.title || 'Viewed item')}</strong><p>${V2.escape(item.type || 'EdgeX activity')} · ${item.timestamp ? V2.escape(new Date(item.timestamp).toLocaleString()) : 'Time unavailable'}</p></div></article>`).join('') : empty('No activity recorded yet', 'Viewed fixtures, markets, and analyses will appear here when activity tracking is enabled.')}</section>`);
  }

  function favorites() { return shell('Account / Favorites', 'Favorites', 'Follow teams, players, leagues, fixtures, markets, crypto assets, and forex pairs in one place.', `<section class="edgex-v2-card">${empty('Nothing followed yet', 'Use the star or follow action on a supported EdgeX item to see it here.')}</section>`); }
  function saved() { const items = stored(V2.STORAGE.saved, []); return shell('Account / Research', 'Saved analysis', 'Keep useful EdgeX explanations close so you can revisit them later.', `<section class="edgex-v2-card">${items.length ? items.map(item => `<article class="edgex-saved-row"><div><strong>${V2.escape(item.subject || item.title || 'Saved analysis')}</strong><p>${V2.escape(item.summary || 'No summary available.')}</p></div><span class="edgex-v2-chip">${V2.escape(item.confidence ? `${item.confidence}% confidence` : 'Confidence unavailable')}</span></article>`).join('') : empty('No saved analysis yet', 'Save an explanation from a supported feature page and it will appear here.')}</section>`); }
  function notifications() { return shell('Account / Alerts', 'Notifications', 'Only useful updates: fixture changes, provider updates, market movement, and analysis refreshes.', `<section class="edgex-v2-card">${empty('You are all caught up', 'Notifications will appear here when a followed item changes.')}</section>`); }
  function history() { const items = stored(V2.STORAGE.activity, []); return shell('Account / History', 'History', 'Review pages and analyses you actually opened in EdgeX.', `<section class="edgex-v2-card">${items.length ? items.map(item => `<article class="edgex-saved-row"><div><strong>${V2.escape(item.subject || item.title || 'Viewed item')}</strong><p>${V2.escape(item.type || 'EdgeX activity')} · ${item.timestamp ? V2.escape(new Date(item.timestamp).toLocaleString()) : 'Time unavailable'}</p></div></article>`).join('') : empty('No history yet', 'Viewed fixtures, markets, players, crypto assets, and forex pairs will appear here when activity tracking is enabled.')}</section>`); }
  function settings() { return shell('Account / Settings', 'Settings', 'Shape EdgeX around the sports, markets, crypto, and forex topics you care about.', `<section class="edgex-v2-card edgex-settings-list">${['General','Appearance','Language & region','Timezone','Notifications','Privacy','AI preferences','Data usage'].map((label, index) => `<label><span><strong>${label}</strong><small>${index === 6 ? 'Choose preferred sports and analysis types.' : 'Available when account settings are connected.'}</small></span><button type="button" class="edgex-setting-action" aria-label="${label} settings">→</button></label>`).join('')}</section>`); }
  function search() { return shell('Discover', 'Search EdgeX', 'Find a supported EdgeX page or topic without digging through the navigation.', `<section class="edgex-v2-card"><div class="edgex-search-box"><input id="edgex-global-search" type="search" placeholder="Search players, teams, fixtures, markets, crypto, forex, or leagues" aria-label="Search EdgeX"><div id="edgex-global-results"></div></div></section>`); }
  root.innerHTML = ({ profile, favorites, saved: saved, notifications, history, settings, search }[page] || profile)(); if (page === 'search') { const dataset = [{ id:'football', name:'Football', type:'Sports', href:'football.html' }, { id:'basketball', name:'Basketball', type:'Sports', href:'basketball.html' }, { id:'markets', name:'Markets Intelligence', type:'Markets', href:'events.html' }, { id:'crypto', name:'Crypto Intelligence', type:'Crypto', href:'crypto.html' }, { id:'forex', name:'Forex Intelligence', type:'Forex', href:'forex.html' }, { id:'weather', name:'Weather Intelligence', type:'Sports context', href:'weather.html' }, { id:'player-edge', name:'Player Edge', type:'Sports context', href:'squads.html' }]; V2.mountSearch(document.getElementById('edgex-global-search'), document.getElementById('edgex-global-results'), dataset, id => { const hit = dataset.find(item => item.id === id); if (hit) location.href = hit.href; }); }
})();
