(() => {
  const root = document.getElementById('markets-root');
  if (!root) return;
  const state = { query: '', category: '', sort: 'newest', markets: [], loading: false, error: '' };
  const esc = value => window.EdgeXV2?.escape ? EdgeXV2.escape(value) : String(value ?? '');
  const num = value => Number.isFinite(Number(value)) ? Number(value) : null;

  function normalise(raw) {
    const outcomes = Array.isArray(raw.outcomes) ? raw.outcomes : [];
    const probability = num(raw.probability || raw.yesPrice || raw.outcome1Price || outcomes[0]?.price);
    return { id: raw.id || raw.eventId || raw.slug || null, question: raw.question || raw.title || raw.name || 'Market question unavailable', category: raw.category || raw.tags?.[0] || null, probability, movement24h: num(raw.movement24h || raw.change24h), aiProbability: null, confidence: null, volume: num(raw.volume || raw.totalVolume), liquidity: num(raw.liquidity), resolutionDate: raw.resolutionDate || raw.closingDate || null, summary: 'EdgeX analysis will appear when enough structured evidence is available.', metadata: raw };
  }

  function toolbar() { return `<div class="edgex-v2-toolbar"><input id="markets-search" type="search" placeholder="Search markets by question" aria-label="Search Markets" value="${esc(state.query)}"><select id="markets-category" aria-label="Filter market category"><option value="">All supported categories</option>${[...new Set(state.markets.map(m => m.category).filter(Boolean))].sort().map(c => `<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select><select id="markets-sort" aria-label="Sort markets"><option value="newest">Newest</option><option value="confidence">Highest confidence</option><option value="movement">24h movement</option><option value="volume">Volume</option></select></div>`; }

  function items() { const q = state.query.toLowerCase().trim(); return state.markets.filter(m => (!q || m.question.toLowerCase().includes(q)) && (!state.category || m.category === state.category)).sort((a,b) => state.sort === 'movement' ? (b.movement24h ?? -Infinity) - (a.movement24h ?? -Infinity) : state.sort === 'volume' ? (b.volume ?? -Infinity) - (a.volume ?? -Infinity) : state.sort === 'confidence' ? (b.confidence ?? -Infinity) - (a.confidence ?? -Infinity) : 0); }

  function card(m) { const p = m.probability === null ? null : `${Math.round(m.probability * (m.probability <= 1 ? 100 : 1))}%`; const move = m.movement24h === null ? 'Unavailable' : `${m.movement24h > 0 ? '+' : ''}${m.movement24h}%`; return `<article class="edgex-v2-card edgex-market-card"><div class="edgex-v2-kicker">${esc(m.category || 'Market')} · Read-only analysis</div><h3>${esc(m.question)}</h3><div class="edgex-market-stats"><div><small>Market probability</small><strong>${p || 'Unavailable'}</strong></div><div><small>24h movement</small><strong>${esc(move)}</strong></div><div><small>EdgeX estimate</small><strong>Unavailable</strong></div><div><small>Confidence</small><strong>Unavailable</strong></div></div><div class="edgex-v2-state"><strong>Analysis pending</strong><span>EdgeX will not invent an estimate without validated context, movement history, and relevant evidence.</span></div><button class="edgex-v2-button market-detail-button" data-market-id="${esc(m.id)}" type="button">View analysis</button></article>`; }

  function render() { const list = items(); root.innerHTML = `<div class="edgex-v2-page-head"><div><span class="edgex-v2-eyebrow">Bayse public data</span><h1>Markets Intelligence</h1><p>Review current public market questions with clear context, source notes, and evidence-aware analysis.</p></div><button class="edgex-v2-button" id="markets-refresh" type="button">Refresh</button></div>${toolbar()}${state.loading ? `<div class="edgex-v2-grid">${[1,2,3].map(() => '<div class="edgex-v2-skeleton"></div>').join('')}</div>` : state.error ? `<div class="edgex-v2-state edgex-v2-state-error"><strong>Markets are unavailable</strong><span>${esc(state.error)}</span><button class="edgex-v2-button" id="markets-retry" type="button">Try again</button></div>` : list.length ? `<div class="edgex-v2-grid">${list.map(card).join('')}</div>` : `<div class="edgex-v2-state"><strong>${state.markets.length ? 'No markets match this search' : 'No market data available'}</strong><span>Try another category or return when the public provider is available.</span></div>`}`;
    document.getElementById('markets-search')?.addEventListener('input', e => { state.query = e.target.value; render(); });
    document.getElementById('markets-category')?.addEventListener('change', e => { state.category = e.target.value; render(); });
    document.getElementById('markets-sort')?.addEventListener('change', e => { state.sort = e.target.value; render(); });
    document.getElementById('markets-refresh')?.addEventListener('click', load); document.getElementById('markets-retry')?.addEventListener('click', load);
    document.querySelectorAll('.market-detail-button').forEach(button => button.addEventListener('click', () => { const market = state.markets.find(item => item.id === button.dataset.marketId); if (market) showDetail(market); }));
    const category = document.getElementById('markets-category'); if (category) category.value = state.category; const sort = document.getElementById('markets-sort'); if (sort) sort.value = state.sort;
  }

  async function showDetail(m) { const dialog = document.createElement('dialog'); dialog.className = 'edgex-v2-dialog'; dialog.innerHTML = `<div class="edgex-v2-card"><button class="edgex-v2-dialog-close" type="button">Close</button><span class="edgex-v2-eyebrow">Market analysis</span><h2>${esc(m.question)}</h2><p>${esc(m.category || 'Category unavailable')} · Resolution ${m.resolutionDate ? esc(new Date(m.resolutionDate).toLocaleString()) : 'unavailable'}</p><div class="edgex-market-stats"><div><small>Market probability</small><strong>${m.probability === null ? 'Unavailable' : `${Math.round(m.probability * (m.probability <= 1 ? 100 : 1))}%`}</strong></div><div><small>AI probability</small><strong id="market-ai-probability">Loading…</strong></div><div><small>Confidence</small><strong id="market-ai-confidence">Loading…</strong></div></div><div class="edgex-v2-state" id="market-ai-state"><strong>Generating a structured read</strong><span>EdgeX will use only the public market context supplied by the provider.</span></div><div id="market-ai-detail"></div></div>`; document.body.appendChild(dialog); dialog.querySelector('.edgex-v2-dialog-close').onclick = () => dialog.remove(); dialog.showModal(); try { const response = await fetch('/api/edge-analysis', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ domain: 'markets', subject: m.question, data: { id: m.id, question: m.question, category: m.category, probability: m.probability, movement24h: m.movement24h, volume: m.volume, liquidity: m.liquidity, resolutionDate: m.resolutionDate, providerData: m.metadata } }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Analysis unavailable'); const probability = result.probability == null ? 'Unavailable' : `${Math.round(Number(result.probability) <= 1 ? Number(result.probability) * 100 : Number(result.probability))}%`; dialog.querySelector('#market-ai-probability').textContent = probability; dialog.querySelector('#market-ai-confidence').textContent = result.confidence == null ? 'Unavailable' : `${result.confidence}%`; dialog.querySelector('#market-ai-state').innerHTML = `<strong>${esc(result.verdict || 'Analysis returned')}</strong><span>${esc(result.dataQuality || 'Data quality unavailable')}</span>`; dialog.querySelector('#market-ai-detail').innerHTML = `<div class="edgex-v2-state"><strong>Why this read</strong><span>${esc((result.reasons || []).join(' ') || 'No supporting reasons returned.')}</span><small>${esc((result.uncertainties || []).join(' ') || 'No additional uncertainty returned.')}</small></div>`; } catch (error) { dialog.querySelector('#market-ai-state').innerHTML = `<strong>Analysis unavailable</strong><span>${esc(error.message || 'The structured analysis service could not respond.')}</span>`; dialog.querySelector('#market-ai-probability').textContent = 'Unavailable'; dialog.querySelector('#market-ai-confidence').textContent = 'Unavailable'; } }

  async function load() { state.loading = true; state.error = ''; render(); try { const response = await fetch('/api/edge-markets?limit=50'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Provider unavailable'); const raw = Array.isArray(body.markets) ? body.markets : []; state.markets = raw.map(normalise); } catch (error) { state.markets = []; state.error = error.message || 'Provider unavailable'; } finally { state.loading = false; render(); } }
  render(); load();
})();
